# Generated by Django 5.2.11 on 2026-02-25 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=200, null=True)),
                ('calories', models.PositiveIntegerField(null=True)),
                ('serving_size', models.CharField(max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='foodlogs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodentries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
