#sign up
POST http://127.0.0.1:8000/register/ 
Content-Type: application/json

{
    "username":"v",
    "email":"v@gmail.com",
    "password":"password@123",
    "phone":12345683811
    
}

#token
###
POST http://127.0.0.1:8000/token/ 
Content-Type: application/json

{
    "username":"v@gmail.com",
    "password":"password@123"
}

#profile create
###
POST http://127.0.0.1:8000/profile/
Content-Type: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

{
    "height":170,
    "weight":65,
    "age":22,
    "gender":"male"
}


#profile retrieve
###
GET http://127.0.0.1:8000/profile/5/
Accept: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

#profile update
###
PUT  http://127.0.0.1:8000/profile/5/update/
Content-Type: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

{
    "height":170,
    "weight":62,
    "age":22,
    "gender":"male"
}

#user details
###
GET http://127.0.0.1:8000/user/8/
Accept: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

#===========FOODLOG==============

#add foodlog
###
POST http://127.0.0.1:8000/foodlog/
Content-Type: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

{

    "name":"dosa",
    "meal_type":"breakfast",
    "calories":300,
    "serving_size":"2"
    
}


#list foodlog
###
GET http://127.0.0.1:8000/foodlog/
Accept: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

#retrieve foodlog
###
GET http://127.0.0.1:8000/foodlog/22/
Accept: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

#update foodlog
###
GET http://127.0.0.1:8000/foodlog/1/
Accept: application/json
Authorization: Token 2a8e2f149043c9c5662d2799cea4b3407bfb21fd

{
  "id": 1,
  "owner": "django",
  "name": "tea",
  "meal_type": "snack",
  "calories": 75,
  "serving_size": "100ml",
  "notes": null,
  "picture": null,
  "created_at": "2026-02-25T06:17:48.339889Z"
}

#delete foodlog
###
DELETE http://127.0.0.1:8000/foodlog/2/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#summary
###
GET http://127.0.0.1:8000/summary/
Accept: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

#diet plan
###
POST http://127.0.0.1:8000/diet-plan/
Content-Type: application/json
Authorization: Token 08b7fec2c7810df9901b822f8cf5ca01b717556a

{

    "goal":"weigth loss",
    "target_weight":185,
    "duration":4
}

