#sign up
POST http://127.0.0.1:8000/register/ 
Content-Type: application/json

{
    "username":"java",
    "email":"java@gmail.com",
    "password":"password@123",
    "phone":1234567896
    
}

#token
###
POST http://127.0.0.1:8000/token/ 
Content-Type: application/json

{
    "username":"java@gmail.com",
    "password":"password@123"
}

#profile create
###
POST http://127.0.0.1:8000/profile/
Content-Type: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

{
    "height":190,
    "weight":85,
    "age":28,
    "gender":"female"
}


#profile retrieve
###
GET http://127.0.0.1:8000/profile/3/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#profile update
###
PUT  http://127.0.0.1:8000/profile/1/update/
Content-Type: application/json
Authorization: Token 7dee5ca583bf29c4ebc748c110da5e4da3cc6c18

{
    "height":180,
    "weight":80,
    "age":28,
    "gender":"male"
}

#user details
###
GET http://127.0.0.1:8000/user/4/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#===========FOODLOG==============

#add foodlog
###
POST http://127.0.0.1:8000/foodlog/
Content-Type: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

{

    "name":"chapathi",
    "meal_type":"dinner",
    "calories":300,
    "serving_size":"5"
    
}


#list foodlog
###
GET http://127.0.0.1:8000/foodlog/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#retrieve foodlog
###
GET http://127.0.0.1:8000/foodlog/5/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#update foodlog
###
GET http://127.0.0.1:8000/foodlog/1/
Accept: application/json
Authorization: Token 2a8e2f149043c9c5662d2799cea4b3407bfb21fd

{
  "id": 1,
  "owner": "django",
  "name": "tea",
  "meal_type": "snack",
  "calories": 75,
  "serving_size": "100ml",
  "notes": null,
  "picture": null,
  "created_at": "2026-02-25T06:17:48.339889Z"
}

#delete foodlog
###
DELETE http://127.0.0.1:8000/foodlog/2/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#summary
###
GET http://127.0.0.1:8000/summary/
Accept: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

#diet plan
###
POST http://127.0.0.1:8000/diet-plan/
Content-Type: application/json
Authorization: Token 1391e7db4aa8872823793b339aa65ccafc440cb3

{

    "goal":"weigth loss",
    "target_weight":185,
    "duration":4
}

